### ISSUE TITLE
[Bug]: SSL certificates not generating

### ISSUE THREAD

**Issue by jaavierdz** [pluja/blogo#13]
### What happened?

The SSL certificates are simply not generating. I cannot access the webpage through the local IP nor my domain, it's been a few hours since I even tried restarting the machine. The docker container seems to be working as seen here:
![image](https://github.com/pluja/blogo/assets/87701524/5e482a0d-e7f9-4dde-aeca-0b4f36a7c1d6)

But chrome says there's a problem with the SSL certificate
![image](https://github.com/pluja/blogo/assets/87701524/75b1bd68-dd4c-459e-918d-001abba18afd)
![image](https://github.com/pluja/blogo/assets/87701524/7e8b31c3-acfe-4e9f-bf0b-f827eb97c776)

### Operating System

Linux

### Relevant log output

```shell
javierdz@javierdz-server:~/blogo-2.1.4$ sudo docker compose up -d
[+] Running 2/2
 ✔ Container blogo  Started                                                                    0.0s
 ✔ Container caddy  Running                                                                    0.0s
```

### Code of Conduct

- [X] I have searched for simmilar issues
- [X] I am sure my issue is related to blogo
- [X] I have searched for the error message on the internet

**Comment by ItsRaelx** [comment]
The SSL itself is not issue with blogo but with caddy. But the site not being accessible is quite weird, can you show your docker-compose.yml?

It would also help if you could tell what exact operating system do you have and if you have latest version of docker.

**Comment by pluja** [comment]
You are trying to generate an SSL certificate with a local IP, which is not possible with Let's Encrypt. Most probably your coputer has pots 80 and 443 closed (your router won't have them open and mapped by default). If you want to generate a local certificate, just change your domain to `blogo.localhost` and caddy will automatically generate a self-signed SSL certificate.

Also, the compose you took from the Wiki has no ports mapped with the host, if you want to connect via IP you should add this to the blogo service in the compose file:

```
ports:
   - 3000:3000
```

as @ItsRaelx said, this issue is not related with blogo, it is related most probably with a bad setup for selfhosting with a domain. I'm closing the issue, but feel free to keep the discussion.

**Comment by pluja** [comment]
Can you share the caddy logs? You can see them with:

```
docker compose logs -f caddy
```

**Comment by pluja** [comment]
I just found the issue, the wiki's docker-compose.yml file was lacking the `caddy` network in the `blogo` service. It's now fixed. To fix your issue, please add the caddy network to the service and restart the containers:

```
services:
[...]
    blogo:
        [...]
        networks:
            - caddy
[...]
```

You can see the complete compose specification in: https://github.com/pluja/blogo/wiki/Hosting-on-your-domain-with-HTTPS#step-2-prepare-the-environment

**Comment by jaavierdz** [comment]
nah, getting the same result. You can check my docker-compose.yml here:


```YAML
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
   
  blogo:
    image: pluja/blogo:latest
    container_name: blogo
    restart: unless-stopped
    volumes:
      - ./articles:/app/articles
    environment:
      # CONFIG
      BLOGO_TITLE: Javierdz | Blog
      BLOGO_DESCRIPTION: Javierdz's blog
      BLOGO_KEYWORDS: blog,open source
      BLOGO_URL: blog.javierdz.xyz
      #BLOGO_ANALYTICS: '<script defer src="https://my.analytics.site/script.js"></script>'
      TIMEZONE: UTC

      # NOSTR CONFIG
      PUBLISH_TO_NOSTR: false
      #NOSTR_NSEC: ""
      #NOSTR_RELAYS: "wss://nostr-pub.wellorder.net,wss://relay.damus.io,wss://relay.nostr.band"

    labels:
      caddy: blog.javierdz.xyz
      caddy.reverse_proxy: "{{upstreams 3000}}"
    
    networks:
      - caddy

networks:
  caddy:
    name: caddy

volumes:
  caddy_data:
```
