### ISSUE TITLE
question: how to setup/install blogo on shared hosting?

### ISSUE THREAD

**Issue by GreenArrowlol** [pluja/blogo#9]
Hi the title says it
how to setup/install blogo on shared hosting?

Do let me know, thanks.

**Comment by pluja** [comment]
You can use Caddy to easily host blogo on a domain.

You will need:

- Docker
- A domain name and the control of its DNS
- A server

First, point your domain to your server so that the SSL certificate can be generated.

Then, create a directory in your server to host the blog files, then in that directory, get the `.env` file:

```
wget https://raw.githubusercontent.com/pluja/blogo/main/example.env -O .env
```

Once you have the `.env` file, edit the contents, most importantly `BLOGO_URL` has to be set to the domain name that you will use (with `https://`).

Then, copy this contents to a file named `docker-compose.yml`:

```
services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:latest
        container_name: caddy
        ports: ["80:80", "443:443"]
        networks: ["caddy"]
        restart: unless-stopped
        volumes:
            - caddy_data:/data
            - /var/run/docker.sock:/var/run/docker.sock:ro
    
    blogo:
        image: pluja/blogo:latest
        container_name: blogo
        networks: ["caddy"]
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./articles:/app/articles
        labels:
            caddy: blogo.example.com
            caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
    caddy:
        name: caddy

volumes:
    caddy_data:
```

Now, make sure to replace `blogo.example.com` with the domain you have pointed to the server and that you will use to access the blog. Also, make sure the DNS are propagated, for example with a look like this: https://dnschecker.org/#A/blogo.site

Finally, once you have everything set up, you can just:

```bash
docker compose up -d
```

Allow a few minutes for the certificate to generate, and you will be able to access blogo at your domain.
